name: Test coverage
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis:5.0.9-alpine
        ports:
          - 6379/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          REDIS_MASTER_SERVICE_HOST: localhost
          REDIS_MASTER_SERVICE_PORT: ${{ job.services.redis.ports[6379] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.4.0
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}